spring:
  config:
    import: key.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/seoul-culture
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        format_sql: true

#spring계층 안에 넣으면 안된다
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace