name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/SeoulCulture/
            sh deploy.sh
